#服务配置
server:
  port: 8088
#spring配置
spring:
  #1.应用配置
  application:
    name: anchor #指定服务名
  #2.数据库连接池
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/anchor?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234

  redis:
    host: localhost
    password:
    port: 6379
    database: 0

  freemarker:
    cache: false
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    template-loader-path: classpath:/templates/       #指定Freemarker模板文件的后缀名

#j2cache:
#  #  config-location: /j2cache.properties
#  open-spring-cache: true
#  cache-clean-mode: passive
#  allow-null-values: true
#  redis-client: lettuce #指定redis客户端使用lettuce，也可以使用Jedis
#  l2-cache-open: true #开启二级缓存
#  broadcast: net.oschina.j2cache.cache.support.redis.SpringRedisPubSubPolicy
#  #  broadcast: jgroups
#  L1: #指定一级缓存提供者为caffeine
#    provider_class: caffeine
#  L2: #指定二级缓存提供者为redis
#    provider_class: net.oschina.j2cache.cache.support.redis.SpringRedisProvider
#    config_section: lettuce
#  sync_ttl_to_redis: true
#  default_cache_null_object: false
#  serialization: fst
#caffeine:
#  properties: /caffeine.properties   # 这个配置文件需要放在项目中
#lettuce:
#  mode: single
#  namespace:
#  storage: generic
#  channel: j2cache
#  scheme: redis
#  hosts: 127.0.0.1:6379
#  password:
#  database: 0
#  sentinelMasterId:
#  maxTotal: 100
#  maxIdle: 10
#  minIdle: 10
#  timeout: 10000
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
authentication:
  user:
    pri-key: pri.key
    pub-key: pub.key



